### ISSUE TITLE
Site greying out on downloading single images

### ISSUE THREAD

**Issue by WeiXie03** [sticky-pi/sticky-pi-api#41]
after clicking opened(in modal) thumbnail and successfully downloading image from server(ComputeCanada) link, browser console: `this.$socket` is `null`, modal buttons don't work and cannot re-invoke any new thumbnail modals/popup from timeline anymore
- [R Shiny Apps Greys Out and Hangs](https://stackoverflow.com/questions/54470702/r-shiny-apps-greys-out-and-hangs)
perhaps some safety feature of Shiny site-serving: grey out when unrecognized interruption to connection, e.g. visiting external link
-> maybe HTML element external links will all break Shiny webapp? for any downloads can only use [Shiny's download buttons](https://shiny.rstudio.com/reference/shiny/1.5.0/downloadButton.html)?
-> site also grey out when invalid user/login, but can't interact with anything

**Comment by qgeissmann** [comment]
just adding `target=”_blank”` to the image works.
