### ISSUE TITLE
TODO: in Image Fetching for Scoping by Selecting Project, Match Specific Device IDs in Addition to Dates

### ISSUE THREAD

**Issue by WeiXie03** [sticky-pi/sticky-pi-api#43]
Currently, when a project selected, image fetching (when user goes to Images, Data tabs) is simply done by feeding date ranges from the project series metadata table into the `api_get_images()` general function for scoping by date range.
However, there may be images and metadata within the date ranges of a project that are not actually part of the project.

**Comment by qgeissmann** [comment]
we now match device id as `api_get_images` talked a `dev` argument, which can be a device id or `"%"` for all devices
